### ISSUE TITLE
brews/gcc48 fails to compile on older Macs

### ISSUE THREAD

**Issue by arvi** [boxen/our-boxen#647] opened 2014-08-09 06:00 UTC
I'm really stuck with this issue for more than a day now. My GCC is already at 2.1.1 in my Puppetfile (https://github.com/arvi/my-boxen/blob/master/Puppetfile) and I'm using --build-from-source option in my manifests/site.pp (https://github.com/arvi/my-boxen/commit/f4e471a588e2d4b35d4766347101794b243c1f31) based on previous researches related to this issue.

I'm doing this on my iMac Mavericks 10.9.4. My boxen is just my clone from currrent https://github.com/boxen/our-boxen with modification in site.pp mentioned above.

Hoping somebody can help me to figure this out... 

$ ./script/boxen --no-fde
Notice: Compiled catalog for imac.local in environment production in 5.01 seconds
Notice: /Stage[main]/Homebrew/File[/opt/boxen/cache/homebrew]/ensure: created
Notice: Package[boxen/brews/gcc48](provider=homebrew): Updating homebrew formulas
Error: Could not update: Execution of 'brew install boxen/brews/gcc48 --build-from-source' returned 1: ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.3/gcc-4.8.3.tar.bz2
==> ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/opt/boxen/homebrew/Cellar/gcc48/4.8.3-boxen1 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-4.8 --with-gmp=/opt/boxen/homebrew/opt/gmp4 --with-mpfr=/opt/boxen/homebrew/opt/mpfr2 --with-mpc=/opt/boxen/homebrew/opt/libmpc08 --with-cloog=/opt/boxen/homebrew/opt/cloog018 --with-isl=/opt/boxen/homebrew/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion=Homebrew gcc48 4.8.3-boxen1 --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
==> make bootstrap
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [all-stage1-target-libstdc++-v3] Error 2
make[1]: **\* [stage1-bubble] Error 2
make: **\* [bootstrap] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/boxen/homebrew-brews/issues
Wrapped exception:
Execution of 'brew install boxen/brews/gcc48 --build-from-source' returned 1: ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.3/gcc-4.8.3.tar.bz2
==> ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/opt/boxen/homebrew/Cellar/gcc48/4.8.3-boxen1 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-4.8 --with-gmp=/opt/boxen/homebrew/opt/gmp4 --with-mpfr=/opt/boxen/homebrew/opt/mpfr2 --with-mpc=/opt/boxen/homebrew/opt/libmpc08 --with-cloog=/opt/boxen/homebrew/opt/cloog018 --with-isl=/opt/boxen/homebrew/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion=Homebrew gcc48 4.8.3-boxen1 --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
==> make bootstrap
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [all-stage1-target-libstdc++-v3] Error 2
make[1]: **\* [stage1-bubble] Error 2
make: **\* [bootstrap] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/boxen/homebrew-brews/issues
Error: /Stage[main]/Gcc/Package[boxen/brews/gcc48]/ensure: change from absent to 4.8.3-boxen1 failed: Could not update: Execution of 'brew install boxen/brews/gcc48 --build-from-source' returned 1: ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.3/gcc-4.8.3.tar.bz2
==> ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/opt/boxen/homebrew/Cellar/gcc48/4.8.3-boxen1 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-4.8 --with-gmp=/opt/boxen/homebrew/opt/gmp4 --with-mpfr=/opt/boxen/homebrew/opt/mpfr2 --with-mpc=/opt/boxen/homebrew/opt/libmpc08 --with-cloog=/opt/boxen/homebrew/opt/cloog018 --with-isl=/opt/boxen/homebrew/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion=Homebrew gcc48 4.8.3-boxen1 --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
==> make bootstrap
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [all-stage1-target-libstdc++-v3] Error 2
make[1]: **\* [stage1-bubble] Error 2
make: **\* [bootstrap] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/boxen/homebrew-brews/issues
Notice: /Package[findutils]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Package[findutils]: Skipping because of failed dependencies
Notice: /Package[ack]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Package[ack]: Skipping because of failed dependencies
Notice: /Package[gnu-tar]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Package[gnu-tar]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/File[/Users/Arvi/src/our-boxen]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/File[/Users/Arvi/src/our-boxen]: Skipping because of failed dependencies
Notice: /Package[readline]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Package[readline]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.2]/Ruby[2.1.2]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.2]/Ruby[2.1.2]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.0]/Ruby[2.1.0]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.0]/Ruby[2.1.0]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[2.0.0]/Ruby::Alias[2.0.0]/Ruby::Version[2.0.0-p451]/Ruby[2.0.0-p451]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[2.0.0]/Ruby::Alias[2.0.0]/Ruby::Version[2.0.0-p451]/Ruby[2.0.0-p451]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[1.9.3]/Ruby::Alias[1.9.3]/Ruby::Version[1.9.3-p545]/Ruby[1.9.3-p545]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[1.9.3]/Ruby::Alias[1.9.3]/Ruby::Version[1.9.3-p545]/Ruby[1.9.3-p545]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[2.0.0]/Ruby::Alias[2.0.0]/File[/opt/rubies/2.0.0]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[2.0.0]/Ruby::Alias[2.0.0]/File[/opt/rubies/2.0.0]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.1]/Ruby[2.1.1]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[2.1.1]/Ruby[2.1.1]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[default]/Ruby::Version[1.9.3]/Ruby::Alias[1.9.3]/File[/opt/rubies/1.9.3]: Dependency Package[boxen/brews/gcc48] has failures: true
Warning: /Stage[main]/Main/Node[default]/Ruby::Version[1.9.3]/Ruby::Alias[1.9.3]/File[/opt/rubies/1.9.3]: Skipping because of failed dependencies

**Comment by seanknox** [comment] 2015-03-21 19:08
@arvi is this still an issue or can it be closed?

**Comment by arvi** [comment] 2015-03-22 03:37
Hi @seanknox, you may close this issue as this seems to be a machine-specific problem based on other comments. After couple of days trying to fix this before, I decided to not use boxen anymore. I had fun experimenting how it works as it used to work before, though behavior was not consistent when I ran it again and would just take a lot of my time instead of focusing to things I need to get done. Thanks!

**Comment by seanknox** [comment] 2015-03-22 03:46
Thanks @arvi. I'm not a maintainer, would you mind closing this?

**Comment by arvi** [comment] 2015-03-22 04:07
Hmmmm, I haven't closed an issue before. Reading this article, I don't have anything to commit or merge. I think the authors of boxen can just close it if they want to. After all they have 475 open issues.

https://guides.github.com/features/issues/
```
By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into master, it will also automatically close the issue.
```

Thanks!

**Comment by seanknox** [comment] 2015-03-22 04:09
@arvi next to the comment button is a "close issue" button. click that.

**Comment by arvi** [comment] 2015-03-22 05:16
@seanknox bummer haha... I was looking for it near the title :p Thanks!

**Comment by seanknox** [comment] 2015-04-13 22:26
Ah, just experienced this for myself on a pair of late 2012 iMacs. None of the workarounds here fixed the issue.

**Comment by tob1k** [comment] 2015-04-13 23:43
Strange- We have several late 2012 27" iMacs that haven't had this problem.

**Comment by leonardoobaptistaa** [comment] 2015-04-17 13:32
@seanknox I had this problem yesterday on a 2011 macbook pro, this is how I managed to fix it:
https://github.com/Homebrew/homebrew-versions/issues/760#issuecomment-93985762

Explanation here:
https://github.com/mriddle/puppet-gcc/releases/tag/2.2.1

**Comment by jacobbednarz** [comment] 2016-11-15 06:21
Closing due to this issue being stale. If you can still reproduce or would like to continue this discussion, please let me know and I'll reopen this.

**Closed by jacobbednarz** 2016-11-15 06:21 UTC
