### ISSUE TITLE
upgrade instructions result in deleting people and projects

### ISSUE THREAD

**Issue by jbcpollak** [boxen/our-boxen#717] opened 2015-02-13 22:47 UTC
When I follow the upgrade instructions:

    rm Puppetfile.lock Gemfile.lock
    bundle install --no-deployment --without development --path .bundle
    bundle exec librarian-puppet install --clean

My `modules/people` and `modules/projects` folders are removed / deleted. This let to a serious amount of stress today. :)

I'm not a Puppet expert, but I think it happens when you run librarian-puppet after removing the Puppetfile.lock

How are we supposed to handle this?

**Comment by tcooper** [comment] 2015-02-13 23:35
This was also my experience and my inelegant solution was to put my `modules/people` and `modules/projects` changes in another branch or my repository. Obviously, I'd like to know how this is supposed to work...

**Comment by seanknox** [comment] 2015-03-21 19:25
@jbcpollak @tcooper I've never seen this. Can you reproduce it and post the steps here?

**Comment by seanknox** [comment] 2015-03-22 18:43
This is strange behavior. As pointed out above, the top-level modules/ is for your personal or project manifests. Boxen modules are all in shared/.

Are any of you modifying Boxen aside from Puppetfile or creating manifests? Trying to understand what's different about your Boxens.

**Comment by tcooper** [comment] 2015-03-23 05:29
Before the last time I updated our-boxen I tucked my personal modules away for safe keeping. The update removed them so I created a branch to store them in and have been running boxen out of the branch since then and haven't updated our-boxen since then because of the problem. When I get a chance I'll merge my branch to master and update to see if the problem can still be reproduced.

**Comment by seanknox** [comment] 2015-03-26 00:01
Sounds good. I'm going to close this for now, but if you discover it to still be an issue feel free to re-open.

**Comment by jbcpollak** [comment] 2015-05-01 03:07
This happened to me again, on a brand new Mac after upgrading following the instructions in the faq.

I am not 100% sure what happened, but here is what I did:

* checked out my master 'our-boxen', where everything is fine
* make a branch
* merged current upstream `our-boxen` into our branch
* resolved conflicts
* At this point I'm reasonably confident our changes were still in place
* ran bundle commands
* ran `./script/boxen`
* Had problems (#740, #741)
* Resolved those problems by manually editing Puppetfile and hacking a file in modules
* ran `./script/boxen`
* At this point, boxen ran cleanly, except I noticed our customized people and projects changes were not applied. 

This is the 3rd time I've had this happen, whenever I follow the upgrade instructions.

**Comment by jbcpollak** [comment] 2015-05-01 04:27
I followed the update instructions in the FAQ (https://github.com/boxen/our-boxen/blob/master/docs/faq.md) with the one exception of using a local branch rather than master. The files were not deleted.

I suspect the files end up deleted after the first run of `./scripts/boxen` after following the upgrade instructions, but I have no idea how boxen works, so I'm not sure if that is a reasonable guess or not.

**Comment by seanknox** [comment] 2015-05-03 03:07
What files were deleted, exactly?

**Comment by jbcpollak** [comment] 2015-05-03 03:29
It appears to be `modules/people` and `modules/projects`. I don't think
anything else is affected.

**Comment by seanknox** [comment] 2015-05-03 22:27
@jbcpollak is your boxen repo publicly accessible? I can't imagine any way this could happen.

**Comment by jbcpollak** [comment] 2015-05-03 23:53
I can give you access, there isn't anything  sensitive in the repo, but it
does reference some private repos I can't share.

**Comment by salimane** [comment] 2015-05-24 20:12
this is caused by ``bundle exec librarian-puppet install --clean``. The ``--clean`` option means delete any file/folder not being managed by ``librarian-puppet``, thus ``Puppetfile``.
You should not use the ``--clean`` if you have files not checked into your repo.
Thanks

**Comment by seanknox** [comment] 2015-05-26 17:18
Thanks. Going to close this, would appreciate a PR to update documentation
if folks think that would be helpful.

**Closed** 2015-05-26 17:20 UTC
Labels: question

**Comment by stereobooster** [comment] 2015-07-20 19:19
I have the same problem. My repo https://github.com/stereobooster/my-boxen

**Comment by jbcpollak** [comment] 2015-07-20 19:53
So I never residences, but I think the probably I had was because of a bad
merge. At some point I merged my master branch with upstream master by
doing a rebase of my changes on top of the upstream master. But maybe I had
some other funky merges before or after that.

Anyway, I cleaned everything up, I think by starting from scratch and
reapplying all of my changes (by cherry picking).

Now when I merge upstream master into my branch, I don't have this problem
anymore.

Also, I noticed my old private matter branch had a lot of committed content
in the modules folder which I don't think upstream master has. After I
fixed the merge, my modules folder is much cleaner.

I'm writing this from my phone and I can't check my repo right now, but I'm
reasonable sure a rebooted merge will help.

On Mon, Jul 20, 2015, 3:20 PM stereobooster <notifications@github.com>
wrote:

> I have the same problem. My repo https://github.com/stereobooster/my-boxen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boxen/our-boxen/issues/717#issuecomment-122995580>.
>
-- 
--
Joshua Chaitin-Pollak
Chief Technology Officer
Assured Labor, Inc.
www.assuredlabor.com
www.empleolisto.com.mx
www.trabalhoja.com.br

**Comment by stereobooster** [comment] 2015-07-20 20:05
https://github.com/rodjek/librarian-puppet

> Librarian-puppet manages your `modules/` directory for you based on your Puppetfile. Your Puppetfile becomes the authoritative source for what modules you require and at what version, tag or branch.

**Comment by stereobooster** [comment] 2015-07-20 20:22
`bundle exec librarian-puppet install` does not remove `modules/people` and `modules/projects`, but it still adds folders to `module` projects

**Comment by stereobooster** [comment] 2015-07-20 21:37
Figured it out. The problem occurs when you working outside of default location.
I was editing in `/Users/name/my/my-boxen`.
When you working in default directory (`/opt/boxen/repo`) everything is back to normal.

**Comment by jbcpollak** [comment] 2015-07-20 22:25
That makes sense, before I shifted my boxen merge around, I has a
~/src/my-boxen directory, but one I finished the merge changes I started
just symlinking /opt/boxen/repo to ~/src

On Mon, Jul 20, 2015, 5:37 PM stereobooster <notifications@github.com>
wrote:

> Figured it out. The problem occurs when you working outside of default
> location.
> I was editing in /Users/name/my/my-boxen.
> When you working in default directory (/opt/boxen/repo) everything is
> back to normal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boxen/our-boxen/issues/717#issuecomment-123051139>.
>
-- 
--
Joshua Chaitin-Pollak
Chief Technology Officer
Assured Labor, Inc.
www.assuredlabor.com
www.empleolisto.com.mx
www.trabalhoja.com.br

**Comment by fculpo** [comment] 2015-08-13 12:27
Same issue here, no matter if i merge into a local branch or master, or if i'm working in the default dir or not.

modules/ gets cleared and filled with modules that apparently should go to shared/

My repo: fculpo/boxen

**Comment by basilfx** [comment] 2015-10-01 16:52
Got the same problem.

Cloned this repo, added `modules/people/*` and `modules/projects/*`, updated Gemfile according to docs  (for boxen 2.8.0 to add OSX 10.11 support) and then my `modules/` folder was truncated and filled with dependencies.

**Comment by mpherg** [comment] 2015-10-09 20:25
Same result here. The only thing that is different is an update to El Capitan.
