### ISSUE TITLE
puppet-unity_cache_server

### ISSUE THREAD

**Issue by bilke** [boxen/our-boxen#403] opened 2013-09-16 15:05 UTC
Puppet module for [Unity Cache Server](http://docs.unity3d.com/Documentation/Manual/AssetCacheServer.html):

https://github.com/bilke/puppet-unity_cache_server

**Comment by seanknox** [comment] 2015-03-21 18:54
@tarebyte @bilke can this be merged in or the issue closed?

**Comment by tarebyte** [comment] 2015-03-22 00:36
I'm sorry @bilke the url is still not valid.

I looked here https://unity3d.com/unity/collaboration
This seems to be the right download url: http://netstorage.unity3d.com/unity/5b98b70ebeb9/CacheServer.zip

**Comment by jacobbednarz** [comment] 2016-11-15 06:21
Closing due to this issue being stale. If you can still reproduce or would like to continue this discussion, please let me know and I'll reopen this.

**Closed by jacobbednarz** 2016-11-15 06:21 UTC
Labels: module
