### ISSUE TITLE
Created a golang module

### ISSUE THREAD

**Issue by cbelk** [boxen/our-boxen#809] opened 2016-03-07 16:23 UTC
https://github.com/cbelk/cbelk-golang

Module for barebones Go installation.  Go downloaded from Google.

**Comment by jacobbednarz** [comment] 2016-03-24 21:21
Thanks for your contribution @cbelk! While this is a great start, I think there are a few of things that need to be mentioned here:

1. `go` can [already be installed](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/go.rb) quite painlessly with homebrew so a module really isn't required.
2. Your module makes some assumptions (such as that everyone is using bash for their shell) which will cause some issues for other shell users.
3. Your module is missing tests. Tests help ensure that your module works as intended across different installations. Check out [`puppet-ruby` specs](https://github.com/boxen/puppet-ruby/tree/master/spec) for some examples.

I'm going to close this one off but feel free to let me know if you have any questions!

**Closed by jacobbednarz** 2016-03-24 21:21 UTC
